#!/bin/sh
#
# Startup script used to initialize the system.
#

cd /etc/rc.d/

#
# Start up the system
#

nice -n -20 ./service start pseudofs
nice -n -20 ./service start modules &
nice -n 19 ./service start misc
nice -n 10 ./service start mounts &
timeout 5 ./service start splash &
nice -n 19 ./service start login
nice -n 1 ./service start rtkit &
nice -n 19 ./service start udev &
nice -n -20 ./service start net-setup &
nice -n -20 ./service start net-wired &
nice -n -20 ./service start zram &
nice -n -20 ./service start sshd &
nice -n 19 ./service start binfmt &
