#!/bin/sh
#
# This script assigns an ip to a network device.
#

. /etc/rc.d/config

start() {
	[ "$NETWORK_DCHP" == "true" ] && dhcpcd -j /tmp/log/dhcp.log && exit

	#until $(ip a show $NETWORK_DEVICE &> /dev/null); do sleep 0.5; done
	udevadm wait /sys/class/net/$NETWORK_DEVICE
	ip link set $NETWORK_DEVICE up
	ip addr add $NETWORK_IPV4/24 broadcast + dev $NETWORK_DEVICE
	ip addr add $NETWORK_IPV6/64 dev $NETWORK_DEVICE
	ip route add default via $NETWORK_GATEWAY dev $NETWORK_DEVICE
	ip link set dev $NETWORK_DEVICE mtu $NETWORK_MTU
}

stop() {
	[ "$NETWORK_DCHP" == "true" ] && pkill dhcp &> /dev/null && exit
	ip route del default dev $NETWORK_DEVICE
	ip addr del $NETADDR/24 broadcast + dev $NETWORK_DEVICE
	ip link set $NETWORK_DEVICE down
}
