#!/bin/sh
#
# This script bridges two network connections.
#

. /etc/rc.d/config

start() {
	ip link add name $BRIDGE_NAME type bridge
	ip link set dev $BRIDGE_NAME up
	[[ -n  $BRIDGE_DEV1 ]] && ip link set dev $BRIDGE_DEV1 up
	[[ -n  $BRIDGE_DEV1 ]] && ip link set $BRIDGE_DEV1 master $BRIDGE_NAME
	[[ -n  $BRIDGE_DEV2 ]] && ip link set dev $BRIDGE_DEV2 up
	[[ -n  $BRIDGE_DEV2 ]] && ip link set $BRIDGE_DEV2 master $BRIDGE_NAME
}

stop() {
	ip link set $BRIDGE_NAME down
	ip link delete $BRIDGE_NAME type bridge
}
