#!/bin/sh
#
# This script sets up ZRAM compressed memory
#

. /etc/rc.d/config

start() {
	modprobe -q zram &> /dev/null
	echo "$ZRAM_ALGORITHM" > /sys/block/zram0/comp_algorithm
	echo $(($ZRAM_SIZE*1024*1024)) > /sys/block/zram0/disksize
	mkswap /dev/zram0 &> /dev/null
	swapon /dev/zram0 -p 10
	echo 200 > /proc/sys/vm/swappiness
	echo 1 > /proc/sys/vm/dirty_ratio
	echo 1 > /proc/sys/vm/dirty_background_ratio
	echo 0 > /proc/sys/vm/watermark_boost_factor
	echo 125 > /proc/sys/vm/watermark_scale_factor
	echo 0 > /proc/sys/vm/page-cluster
	echo 2048 > /proc/sys/vm/min_free_kbytes
}

stop() {
	swapoff /dev/zram0
	echo 1 > /sys/block/zram0/reset
	modprobe -qr zram
	echo 60 > /proc/sys/vm/swappiness
	echo 10 > /proc/sys/vm/dirty_ratio
	echo 20 > /proc/sys/vm/dirty_background_ratio
}
